[package]
name = "andromeda-finance"
version = "0.1.0"
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.1.6", features = ["stargate"] }
cosmwasm-schema = { version = "1.1.6" }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw20 = "0.16.0"
schemars = "0.8.10"
cw-utils = "0.16.0"

common = { path = "../common", version = "0.1.0" }
amp = { path = "../amp", version = "0.1.0" }


