[package]
name = "andromeda-ibc"
version = "0.1.0"
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.1.4", features = ["stargate"] }
cosmwasm-schema = "1.1"
cw-storage-plus = "0.15"
cw-utils = "0.15"
cw2 = "0.15"
cw721 = "0.15"
cw721-base = { version = "0.15", features = ["library"] }
thiserror = "1"
serde = "1.0"
cw-paginate = { git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v2.0.0-beta" }
cw721-proxy-derive = { git = "https://github.com/0xekez/cw721-proxy.git" }
cw-cii = { git = "https://github.com/public-awesome/ics721.git" }
cw-pause-once = { git = "https://github.com/public-awesome/ics721.git" }

common = { path = "../common", version = "0.1.0" }
cw-asset = { version = "2.0.0" }

