[package]
name = "andromeda-swapper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.1.0"
cosmwasm-schema = "1.1.0"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.10"
cw-storage-plus = "0.15.0"
cw20 = "0.15.0"
cw2 = "0.15.0"
cw-asset = "2.0.0"
semver = "1"

andromeda-ecosystem = { version = "0.1.0", path = "../../../packages/andromeda-ecosystem" }
common = { version = "0.1.0", path = "../../../packages/common" }
ado-base = { path = "../../../packages/ado-base", version = "0.1.0", features = ["instantiate"] }

[dev-dependencies]
prost = "0.9.0"
andromeda-testing = { version = "0.1.0", path = "../../../packages/andromeda-testing" }
