[package]
name = "ado-base"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
withdraw = ["cw-asset", "cw20"]
modules = []
instantiate = ["primitive"]
primitive = []

[dependencies]
cosmwasm-std = "1.1.0"
cosmwasm-schema = "1.1.0"
cw-storage-plus = "0.15.0"
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
common = { version = "0.1.0", path = "../../packages/common" }
cw2 = "0.15.0"
semver = "1"

cw20 = { version = "0.15.0", optional = true}
cw-asset = { version = "2.0.0", optional = true }

[dev-dependencies]
cw20 = "0.15.0"
