[package]
name = "andromeda-os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
cw-storage-plus = "0.16.0"
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
common = { version = "0.1.0", path = "../../packages/common" }
cw2 = "0.16.0"
semver = "1"
amp = { version = "0.1.0", path = "../amp" }
cw20 = { version = "0.16.0", optional = true}
cw-asset = { version = "2.0.0", optional = true }
regex = "1"
lazy_static = "1"

[dev-dependencies]
cw20 = "0.16.0"
