[package]
name = "andromeda-cw-json"
version = "0.1.1"
authors = ["Anshudhar Kumar Singh <anshudhar2001@gmail.com>"]
edition = "2021"

description = "JSON Parser for CosmWasm using serde_cw_value"
readme = "README.md"
keywords = ["serde", "wasm", "json"]


[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde-cw-value = { version = "^0.7.0" }
thiserror = { version = "2.0.17", default-features = false }


[dev-dependencies]
serde_derive = "^1.0.210"
